// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pipeline.Core.Data;

#nullable disable

namespace Pipeline.Core.Migrations
{
    [DbContext(typeof(PipelineDbContext))]
    [Migration("20260124142018_SeedValueCardTemplates")]
    partial class SeedValueCardTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pipeline.Core.Entities.Content.LabelRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConditionField")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConditionOperator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConditionValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LabelIcon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LabelText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("label_rules", "content");
                });

            modelBuilder.Entity("Pipeline.Core.Entities.Content.NeighborhoodProse", b =>
                {
                    b.Property<string>("NisCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("QualityScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal?>("SeoQualityScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("NisCode");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("neighborhood_prose", "content");
                });

            modelBuilder.Entity("Pipeline.Core.Entities.Content.ValueCardTemplate", b =>
                {
                    b.Property<string>("CardType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CardType");

                    b.ToTable("value_card_templates", "content");

                    b.HasData(
                        new
                        {
                            CardType = "DogParks",
                            SortOrder = 1,
                            Title = "Hondenparken"
                        },
                        new
                        {
                            CardType = "Parks",
                            SortOrder = 2,
                            Title = "Parken"
                        },
                        new
                        {
                            CardType = "Vets",
                            SortOrder = 3,
                            Title = "Dierenartsen"
                        },
                        new
                        {
                            CardType = "PetStores",
                            SortOrder = 4,
                            Title = "Dierenwinkels"
                        },
                        new
                        {
                            CardType = "Supermarkets",
                            SortOrder = 5,
                            Title = "Supermarkten"
                        },
                        new
                        {
                            CardType = "Transit",
                            SortOrder = 6,
                            Title = "Openbaar vervoer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
